=== susannakummer/mite_schema_sk/mite_schema/schema/entry.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "Minimum Information about a Tailoring Enzyme/Maturase Data Standard",
  "additionalProperties": false,
  "required": [
    "accession",
    "status",
    "changelog",
    "enzyme",
    "reactions"
  ],
  "properties": {
    "accession": {
      "title": "MITE accession number/identifier.",
      "$ref": "#/$defs/accession"
    },
    "status": {
      "title": "Track status of entry.",
      "$ref": "#/$defs/status"
    },
    "retirementReasons": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "comment": {
      "title": "Any additional information about this entry",
      "type": "string"
    },
    "changelog": {
      "title": "Log tracking changes in entry.",
      "type": "array",
      "additionalProperties": false,
      "items": {
        "type": "object",
        "required": [
          "version",
          "date",
          "comment",
          "contributors",
          "reviewers"
        ],
        "additionalProperties": false,
        "properties": {
          "version": {
            "title": "The version of the entry.",
            "$ref": "#/$defs/version"
          },
          "date": {
            "title": "The date of the modification.",
            "type": "string",
            "format": "date"
          },
          "comment": {
            "title": "A brief summary of changes.",
            "type": "string"
          },
          "contributors": {
            "title": "A list of identifiers of submitters.",
            "type": "array",
            "items": {
              "title": "An ORCID identifier",
              "type": "string"
            },
            "minItems": 1,
            "uniqueItems": true
          },
          "reviewers": {
            "title": "A list of identifiers of reviewers.",
            "type": "array",
            "items": {
              "title": "An ORCID identifier",
              "type": "string"
            },
            "minItems": 1,
            "uniqueItems": true
          }
        }
      }
    },
    "enzyme": {
      "title": "(Meta)data about the enzyme described by entry.",
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "databaseIds",
        "references"
      ],
      "properties": {
        "name": {
          "title": "Protein name, e.g. 'NisB'.",
          "type": "string"
        },
        "description": {
          "title": "Brief description of the enzyme function.",
          "type": "string"
        },
        "cofactors": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "inorganic": {
              "title": "One or more inorganic cofactors (ions).",
              "type": "array",
              "minItems": 1,
              "uniqueItems": true,
              "items": {
                "$ref": "#/$defs/inorganic"
              }
            },
            "organic": {
              "title": "One or more organic cofactors (coenzymes/cosubstrates/prosthetic groups).",
              "type": "array",
              "minItems": 1,
              "uniqueItems": true,
              "items": {
                "$ref": "#/$defs/organic"
              }
            }
          }
        },
        "databaseIds": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "uniprot": {
              "$ref": "#/$defs/uniprot"
            },
            "genpept": {
              "$ref": "#/$defs/genpept"
            },
            "mibig": {
              "$ref": "#/$defs/mibig"
            },
            "wikidata": {
              "$ref": "#/$defs/wikidata"
            }
          }
        },
        "auxiliaryEnzymes": {
          "title": "Specify any required auxiliary enzymes that are co-forming the maturation machinery.",
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "name": {
                "title": "Protein name, e.g. 'NisC'.",
                "type": "string"
              },
              "description": {
                "title": "Brief description of function.",
                "type": "string"
              },
              "databaseIds": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "uniprot": {
                    "$ref": "#/$defs/uniprot"
                  },
                  "genpept": {
                    "$ref": "#/$defs/genpept"
                  },
                  "wikidata": {
                    "$ref": "#/$defs/wikidata"
                  }
                }
              }
            }
          }
        },
        "references": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/citation"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "taxid": {
          "$ref": "#/$defs/taxid"
                  }
      }
    },
    "reactions": {
      "title": "One or more reactions associated with enzyme.",
      "type": "array",
      "minItems": 1,
      "items": {
        "additionalProperties": false,
        "required": [
          "tailoring",
          "reactionSMARTS",
          "reactions",
          "evidence"
        ],
        "properties": {
          "tailoring": {
            "title": "Ontology-derived tailoring/maturation reaction term.",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
              "$ref": "#/$defs/tailoringFunction"
            }
          },
          "description": {
            "title": "Additional information about tailoring/maturation reaction.",
            "type": "string"
          },
          "evidence": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "evidenceCode",
              "references"
            ],
            "properties": {
              "evidenceCode": {
                "title": "Evidence for enzymatic reaction and substrate specificity",
                "type": "array",
                "minItems": 1,
                "items": {
                  "$ref": "#/$defs/evidence"
                }
              },
              "references": {
                "type": "array",
                "items": {
                  "$ref": "#/$defs/citation"
                },
                "minItems": 1,
                "uniqueItems": true
              }
            }
          },
          "databaseIds": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "rhea": {
                "$ref": "#/$defs/rhea"
              },
              "ec": {
                "$ref": "#/$defs/ec"
              }
            }
          },
          "reactionSMARTS": {
            "title": "A reaction SMARTS pattern describing the (sub)structure to match and the reaction to perform.",
            "$ref": "#/$defs/reactionsmarts"
          },
          "reactions": {
            "type": "array",
            "title": "Substrate -> product(s) resulting from application of reaction SMARTS rule.",
            "minItems": 1,
            "items": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "substrate",
                "products",
                "isIntermediate"
              ],
              "properties": {
                "substrate": {
                  "title": "Substrate (sub)structure as SMILES",
                  "type": "string"
                },
                "products": {
                  "title": "One or more product (sub)structures as SMILES",
                  "type": "array",
                  "minItems": 1,
                  "items": {
                    "type": "string"
                  }
                },
                "forbidden_products": {
                  "title": "Product (sub)structures as SMILES that are absolutely forbidden to occur.",
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "isIntermediate": {
                  "title": "Is this validated reaction an intermediate step (i.e. not the final product)?",
                  "type": "boolean"
                },
                "description": {
                  "title": "Additional information about reaction example",
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "$defs": {
    "accession": {
      "type": "string",
      "pattern": "^MITE\\d{7}$"
    },
    "status": {
      "type": "string",
      "enum": ["pending", "active", "retired"]
    },
    "version": {
      "type": "string",
      "pattern": "^\\d+$"
    },
    "citation": {
      "type": "string",
      "pattern": "^doi:10\\."
    },
    "uniprot": {
      "title": "Uniprot ID reference.",
      "type": "string",
      "pattern": "^[A-Z0-9]+$"
    },
    "genpept": {
      "title": "GenBank GenPept ID (= protein ID, GenBank gene products)",
      "type": "string",
      "pattern": "^[A-Z]{3}[0-9]{5,7}\\.[0-9]+$"
    },
    "mibig": {
      "title": "MIBiG ID reference",
      "type": "string",
      "pattern": "^BGC\\d{7}$|^new\\d+$"
    },
    "wikidata": {
      "title": "Wikidata reference",
      "type": "string",
      "pattern": "^Q\\d+$"
    },
    "rhea": {
      "title": "RHEA cross-reference",
      "type": "string",
      "pattern": "^(\\d+)$"
    },
    "ec": {
      "title": "EC number (2-4 identifiers)",
      "type": "string",
      "pattern": "^[0-9]+(\\.[0-9]+){0,3}$"
    },
    "reactionsmarts": {
      "type": "string",
      "pattern": "^.+>>.+$"
    },
    "evidence": {
      "type": "string",
      "enum": [
        "Chemical probe",
        "Heterologous expression",
        "Inference from genomic data and chemical structure",
        "In vitro assay",
        "Isothermal titration calorimetry",
        "Knock-out studies",
        "Site-directed mutagenesis",
        "Surface plasmon resonance"
      ]
    },
    "inorganic": {
      "type": "string",
      "enum": [
        "Cu",
        "Fe",
        "Mg",
        "Mn",
        "Mo",
        "Ni",
        "Zn",
        "FeS"
      ]
    },
    "organic": {
      "type": "string",
      "enum": [
        "Ascorbic acid",
        "a-Ketoglutaric acid",
        "Adenosine triphosphate",
        "Biotin",
        "Cobalamin",
        "Coenzyme A",
        "Coenzyme B",
        "Coenzyme F420",
        "Coenzyme M",
        "Coenzyme Q10",
        "Cytidine triphosphate",
        "FAD",
        "Flavin mononucleotide",
        "Folate",
        "Glutathione",
        "Heme",
        "Lipoamide",
        "Methylcobalamin",
        "Menaquinone",
        "Methanofuran",
        "Molybdopterin",
        "NAD",
        "NADP",
        "PAPS",
        "Pyridoxal phosphate",
        "Pyrroloquinoline quinone",
        "SAM",
        "Tetrahydrobiopterin",
        "Tetrahydrofolic acid",
        "Tetrahydromethanopterin",
        "Thiamine pyrophosphate"
      ]
    },
    "tailoringFunction": {
      "type": "string",
      "enum": [
        "Acetylation",
        "Acylation",
        "Amination",
        "Biaryl bond formation",
        "Carboxylation",
        "Cyclization",
        "Deamination",
        "Decarboxylation",
        "Dehydration",
        "Dehydrogenation",
        "Demethylation",
        "Dioxygenation",
        "Epimerization",
        "Epoxidation",
        "Glycosylation",
        "Halogenation",
        "Heterocyclization",
        "Hydrolysis",
        "Hydroxylation",
        "Macrolactam formation",
        "Methylation",
        "Monooxygenation",
        "Oxidation",
        "Phosphorylation",
        "Prenylation",
        "Reduction",
        "Ring contraction",
        "Ring expansion",
        "Sulfation",
        "Sulfonation",
        "Other"
      ]
    },
    "taxid": {
      "title": "Taxonomy ID",
      "type": "string",
      "pattern": "^(\\d+)$"
    }
  }
}

=== susannakummer/mite_schema_sk/tests/example_files/example_valid.json
{
    "accession": "MITE0000055",
    "status": "pending",
    "changelog": [
        {
            "version": "1",
            "contributors": [
                "G42B4RI57WLTDHDCD4PMU3MJ",
                "C62OJVVH7XOTOTFZSJT727YU"
            ],
            "reviewers": [
                "BBBBBBBBBBBBBBBBBBBBBBBB"
            ],
            "date": "2024-07-23",
            "comment": "Initial entry."
        },
        {
            "version": "2",
            "contributors": [
                "BBBBBBBBBBBBBBBBBBBBBBBB"
            ],
            "reviewers": [
                "BBBBBBBBBBBBBBBBBBBBBBBB"
            ],
            "date": "2024-11-23",
            "comment": "Some minor changes."
        }
    ],
    "enzyme": {
        "name": "McjC",
        "description": "Lassopeptide ATP-dependent lactam synthetase (C-protein, asparagine synthetase-like)",
        "databaseIds": {
            "uniprot": "Q9X2V9",
            "genpept": "AAD28496.1",
            "mibig": "BGC0000581"
        },
        "references": [
            "doi:10.1128/jb.181.8.2659-2662.1999",
            "doi:10.1002/cbic.201200016"
        ],
        "cofactors": {
            "inorganic": [
                "Fe"
            ],
            "organic": [
                "Heme"
            ]
        },
        "auxiliaryEnzymes": [
            {
                "name": "McjB",
                "description": "Lassopeptide cysteine protease. Required for macrolactam-synthethase function (folds and cleaves precursor peptide)",
                "databaseIds": {
                    "uniprot": "Q9X2V8",
                    "genpept": "AAD28495.1",
                    "wikidata": "Q24776184"
                }
            }
        ],
        "taxid": "1883"
    },
    "reactions": [
        {
            "tailoring": [
                "Macrolactam formation"
            ],
            "description": "Lassopeptide macrolactam formation after N-terminal cleavage: NH2-G-G-X-X-X-X-X-E-Xn-COOH.",
            "reactionSMARTS": "[#6:55]-[#6:54](-[#7:56]-[#6:57](=[O:58])-[#6:59]-[#7:60]-[#6:61](=[O:62])-[#6:63]-[#7:64])-[#6:52](=[O:53])-[#7:51]-[#6:50]-[#6:48](=[O:49])-[#7:47]-[#6@@H:40](-[#6:41]-[c:42]1[c:43][n:44][c:45][n:46]1)-[#6:38](=[O:39])-[#7:37]-[#6@@H:36](-[#6:65])-[#6:34](=[O:35])-[#7:33]-[#6:32]-[#6:30](=[O:31])-[#7:29]-[#6@@H:23](-[#6:24]-[#6:25]-[#6:26](-[#8:28])=[O:27])-[#6:21](=[O:22])-[#7:20]-[#6@@H:18](-[#6:19])-[#6:16](=[O:17])-[#7:15]-[#6@@H:13](-[#6:14])-[#6:11](=[O:12])-[#7:10]-[#6:9]-[#6:7](=[O:8])-[#7:6]-[#6:5]-[#6:3](=[O:4])-[#7:2]-[#6:1]-[#6:66](=[O:67])-[#7:68]-[#6:69]-[#6:70](=[O:71])-[#7:72]-[#6:73]-[#6:74](=[O:75])-[#7:76]-[#6@@H:77](-[#6:111])-[#6:78](=[O:79])-[#7:80]-[#6@@H:81](-[#6:110])-[#6:82](=[O:83])-[#7:84]-[#6@@H:85](-[#6:86])-[#6:87](=[O:88])-[#7:89]-[#6@@H:90](-[#6:91])-[#6:92](=[O:93])-[#7:94]-[#6@@H:95](-[#6:96]-[c:97]1[c:98][c:99][c:100][c:101][c:102]1)-[#6:103](=[O:104])-[#7:105]-[#6:106]-[#6:107](-[#8:109])=[O:108]>>[#6:111]-[#6@H:77](-[#7:76]-[#6:74](=[O:75])-[#6:73]-[#7:72]-[#6:70](=[O:71])-[#6:69]-[#7:68]-[#6:66](=[O:67])-[#6:1]-[#7:2]-[#6:3](=[O:4])-[#6:5]-[#7:6]-[#6:7](=[O:8])-[#6:9]-[#7:10]-[#6:11](=[O:12])-[#6@H:13](-[#6:14])-[#7:15]-[#6:16](=[O:17])-[#6@H:18](-[#6:19])-[#7:20]-[#6:21](=[O:22])-[#6@@H:23]-1-[#6:24]-[#6:25]-[#6:26](=[O:27])-[#7:64]-[#6:63]-[#6:61](=[O:62])-[#7:60]-[#6:59]-[#6:57](=[O:58])-[#7:56]-[#6:54](-[#6:55])-[#6:52](=[O:53])-[#7:51]-[#6:50]-[#6:48](=[O:49])-[#7:47]-[#6@@H:40](-[#6:41]-[c:42]2[c:43][n:44][c:45][n:46]2)-[#6:38](=[O:39])-[#7:37]-[#6@@H:36](-[#6:65])-[#6:34](=[O:35])-[#7:33]-[#6:32]-[#6:30](=[O:31])-[#7:29]-1)-[#6:78](=[O:79])-[#7:80]-[#6@@H:81](-[#6:110])-[#6:82](=[O:83])-[#7:84]-[#6@@H:85](-[#6:86])-[#6:87](=[O:88])-[#7:89]-[#6@@H:90](-[#6:91])-[#6:92](=[O:93])-[#7:94]-[#6@@H:95](-[#6:96]-[c:97]1[c:98][c:99][c:100][c:101][c:102]1)-[#6:103](=[O:104])-[#7:105]-[#6:106]-[#6:107](-[#8:109])=[O:108]",
            "databaseIds": {
                "rhea": "5678",
                "ec": "1.2"
            },
            "reactions": [
                {
                    "substrate": "CC[C@H](C)[C@H](NC(=O)CNC(=O)[C@@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](Cc1ccc(O)cc1)NC(=O)[C@H](CCC(=O)O)NC(=O)[C@@H]1CCCN1C(=O)[C@@H](NC(=O)[C@H](Cc1c[nH]cn1)NC(=O)CNC(=O)[C@H](C)NC(=O)CNC(=O)CN)C(C)C)C(C)C)C(=O)NCC(=O)N[C@H](C(=O)N1CCC[C@H]1C(=O)N[C@H](C(=O)N[C@@H](CO)C(=O)N[C@@H](Cc1ccccc1)C(=O)N[C@@H](Cc1ccc(O)cc1)C(=O)NCC(=O)O)[C@@H](C)CC)[C@@H](C)O",
                    "products": [
                        "CC[C@H](C)[C@H](NC(=O)CNC(=O)[C@@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](Cc1ccc(O)cc1)NC(=O)[C@@H]1CCC(=O)NCC(=O)NCC(=O)N[C@@H](C)C(=O)NCC(=O)N[C@@H](Cc2c[nH]cn2)C(=O)N[C@@H](C(C)C)C(=O)N2CCC[C@H]2C(=O)N1)C(C)C)C(=O)NCC(=O)N[C@H](C(=O)N1CCC[C@H]1C(=O)N[C@H](C(=O)N[C@@H](CO)C(=O)N[C@@H](Cc1ccccc1)C(=O)N[C@@H](Cc1ccc(O)cc1)C(=O)NCC(=O)O)[C@@H](C)CC)[C@@H](C)O"
                    ],
                    "forbidden_products": [
                        "CCCC"
                    ],
                    "isIntermediate": false,
                    "description": "Lasso macrocyclisation of microcin J25 after precursor cleavage, leading to mature product."
                }
            ],
            "evidence": {
                "evidenceCode": [
                    "Site-directed mutagenesis",
                    "Heterologous expression",
                    "Chemical probe"
                ],
                "references": [
                    "doi:10.1074/jbc.M803995200"
                ]
            }
        }
    ]
}
